version: '3.8'
services:
  neo4j:
    image: neo4j:5-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      # ⚠️ Remember to change 'password' to a secure password
      - NEO4J_AUTH=neo4j/Ayush@321
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

    healthcheck:
      # This command checks if the Neo4j HTTP endpoint is responsive.
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      # This command uses the redis-cli to ping the server.
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30